playground/urls.py
from django.urls import path
from playground import views

app_name="first_app"

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('musician_details/<pk>/', views.MusicianDetail.as_view(), name='musician_details'),
    path('add_musician/', views.AddMusician.as_view(), name='add_musician'),
    path('musician_update/<pk>/', views.UpdateMusician.as_view(), name='musician_update'),
    path('delete_musician/<pk>/', views.DeleteMusician.as_view(), name='delete_musician'),
] 

storefront/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('playground.urls')),
]

playground/models.py
from django.db import models
from django.urls import reverse

class Musician(models.Model):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)
    def __str__(self):
        return self.first_name + " "+self.last_name
    
    def get_absolute_url(self):
        return reverse("first_app:musician_details", kwargs={'pk': self.pk})
    
    
class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete = models.CASCADE , related_name='album_list')
    name = models.CharField(max_length = 100)
    release_date = models.DateField()
    
    rating=(
        (1,"Worst"),
        (2,"Bad"),
        (3,"Not Bad"),
        (4,"Good"),
        (5,"Excellent"),
    )
    
    num_stars = models.IntegerField(choices=rating)
    

playground/forms.py
from django import forms
from playground import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields="__all__"
class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model=models.Album
        fields="__all__"

playground/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View,TemplateView, ListView,DetailView,CreateView,UpdateView, DeleteView
from playground import models
from django.urls import reverse_lazy
class IndexView(ListView):
    context_object_name = 'musician_list'
    model = models.Musician
    template_name = 'playground/index.html'


class MusicianDetail(DetailView):
    context_object_name = 'musician'
    model = models.Musician
    template_name = 'playground/musician_details.html'
    
    
class AddMusician(CreateView):
    fields = ('first_name','last_name','instrument')
    model= models.Musician
    template_name = 'playground/musician_form.html'
    

class UpdateMusician(UpdateView):
    fields = ('first_name','instrument')
    model= models.Musician
    template_name = 'playground/musician_form.html'
    
class DeleteMusician(DeleteView):
    context_object_name= 'musician'
    model= models.Musician
    success_url = reverse_lazy("first_app:index")
    template_name = 'playground/delete_musician.html'

playground/templates/playground/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container mt-3 navbar-dark">
  <h2>Navigation Tabs</h2>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{%url 'first_app:index'%}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{%url 'first_app:add_musician'%}">Add Musician</a>
    </li>
  </ul>
</div>
<div class="container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>

playground/templates/playground/delete_musician.html
{% extends 'playground/base.html' %}
{% block body_block %}
<h3>Delete {{musician.first_name}} {{musician.last_name}}?</h3>
<form method="POST">
    {% csrf_token %}
    <input type="submit" name="submit" value="Delete" class="btn btn-danger btn-sm">
    <a href=" {% url 'first_app:musician_details' pk=musician.pk %}" class="btn btn-info btn-sm">Cancel</a> 
</form>
{% endblock  %}

playground/templates/playground/index.html
{% extends 'playground/base.html' %}
{% block body_block %}
<h3>List of Musicians</h3>
<ul>
    {%if musician_list%}
    {%for musician in musician_list%}
        <li>
            <a href="{% url 'first_app:musician_details' pk=musician.pk  %}">
                {{musician.first_name}} 
                {{musician.last_name}}
            </a>
        </li>

    {%endfor%}
    {% else %}
    <h4>No Musician in The List</h4>
    {% endif %}
</ul>
{% endblock  %}

playground/templates/playground/musician_details.html
{% extends 'playground/base.html' %}
{% block body_block %}
<h3>Musicians Details</h3>
<p>{{musician.first_name}} {{musician.last_name}}</p>
<p>{{musician.instrument}}</p>
<h3>Album</h3>
<ul>
{% for album in musician.album_list.all %}
    <li>{{album.name}}</li>
{% endfor %}
</ul>
<a href="{% url 'first_app:musician_update'  pk=musician.pk%}" class="btn btn-warning btn-sm">Update</a>
<a href="{% url 'first_app:delete_musician'  pk=musician.pk%}" class="btn btn-danger btn-sm">Delete</a>
{% endblock  %}

playground/templates/playground/musician_form.html
{% extends 'playground/base.html' %}
{% block body_block %}
{% if form.instance.pk %}
<h3>Update Musician</h3>
<form method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-primary btn-sm">
</form>
{% else %}
<h3>Add New Musician</h3> 
<form method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="add" class="btn btn-primary btn-sm">
</form>
{% endif %}
{% endblock  %}

templates/playground/album_form.html
{% extends 'playground/base.html' %}
{% block body_block %}
<h3>Album Form:</h3>
<form method="POST">
    {{album_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="add" class="btn btn-primary btn-sm">
</form>

{% endblock  %}

templates/playground/album_list.html
{% extends 'playground/base.html' %}
{% block body_block %} 
<h6>Artist Name : {{artist_info.first_name}} {{artist_info.last_name}}</h6>
<h6>Instrument : {{artist_info.instrument}}</h6>
<h6>Artist Rating : {{artist_rating.num_stars__avg}}</h6>
<a href="{% url 'first_app:edit_artist' id=artist_info.id  %}" class="btn btn-success btn-sm">Edit</a>
<a href="{% url 'first_app:delete_musician' id=artist_info.id  %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete the Musician?')">Delete</a>
<h3>Album List</h3>
<table class="table table-bordered">
    <tr>
        <th>Album Name</th>
        <th>Release date</th>
        <th> Rating</th>
    </tr>
    {% for album in album_list %}
    <tr>
        <td><a href="{%url 'first_app:edit_album' id=album.id%}">{{album.name}}</a></td>
        <td>{{album.release_date|date:"M d, Y"}}</td>
        <td>{{album.num_stars}}</td>
    </tr>
    {% endfor %}
{% endblock  %}

templates/playground/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container mt-3 navbar-dark">
  <h2>Navigation Tabs</h2>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{%url 'first_app:index'%}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{%url 'first_app:musician_form'%}">Add Musician</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{%url 'first_app:album_form'%}">Add Album</a>
    </li>
  </ul>
</div>
<div class="container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>

templates/playground/delete.html
{% extends 'playground/base.html' %}
{% block body_block %}
{%if delete_success%}
<div class='alert alert-danger'>{{delete_success}}</div>
{% endif %}
{% endblock  %}

templates/playground/edit_album.html
{% extends 'playground/base.html' %}
{% block body_block %}
<h3>Edit Album</h3>
{%if success_text%}
<div class='alert alert-success'>{{success_text}}</div>
{% endif %}
<form method="POST">
    {{edit_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
    <a href="{% url 'first_app:delete_album' id=album_id%}" class="btn btn-danger btn-sm" onclick="return confirm('Delete this Album?')">Delete</a>
</form>
{% endblock  %}

templates/playground/edit_artist.html
{% extends 'playground/base.html' %}
{% block body_block %} 
<h4>Edit Artist</h4>
<form method="POST">
    {{edit_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>
{% endblock  %}

templates/playground/index.html
{% extends 'playground/base.html' %}
{% block body_block %}
<h3>List of Musicians</h3>
<ul>
    {%if musician_list%}
    {%for musician in musician_list%}
        <li><a href="{% url 'first_app:album_list' id=musician.id%}">{{musician.first_name}} {{musician.last_name}}</a></li>

    {%endfor%}
    {% else %}
    <h4>No Musician in The List</h4>
    {% endif %}
</ul>
{% endblock  %}